### ISSUE TITLE
Cannot get "SearchTerm" API command work

### ISSUE THREAD

**Issue by eric-dev** [z1c0/FsApi#3]
Hi,
Thank you very much for this nice and well architectured API. I appreciate it a lot.

I just encounter 1 problem: 
The SEARCH command ("**netRemote.nav.searchTerm**") call using Client::**SearchTermNavList**("searchterm") returns just "S_OK" but no list of found stations as search result. I also tried to call GetNavigMenuItems just after but that still returns the menu's content.

Is there a special way to get a list of results as "navitems", or is this simply not working?
Thanks and Regards,
Eric (eric.dev@laposte.net)

**Comment by tichachm** [comment]
Hi,
the Search is a little bit complicated. 
First you have to send the Search request:
  await RadioClient.searchTermNavList(TextInputText)
after that you nee to select the "Search" Item in the current list:
  await RadioClient.setNavigtion(requestUserSearchInputKey);
at the end, reload the list:
  await RadioClient.getMenuList(startIndex, maxItems)

Note:
You can only use search if the Radio offers an "Search" Menu Entry in the current loaded List, requestUserSearchInputKey is the Key of this entry.
I also realized that some devices may not support Search at all (user feedback). If you have a Windows 10 device you can test Search with my app RadioRemote (it is also using this library).

By the way:
I found your Application FSRadio-Remote, nice work. If you are interested in exchange of experience you can contact me (http://christian.mittring-mering.de/index.php?page=kontakt). My next big thing is to simplify scrolling through a list with more thousands of entries if search is not available.

Thanks
Christian

**Comment by eric-dev** [comment]
Hi,
Thank you for explaning this advanced feature. That was indeed not intuitive but the method definitely works. I'm going to tell more by e-mail.
Regards,
Eric
